name: Deploy 

on:
  push:
    branches:
      - main

env:
  WORKFLOW_ENV: hello_world

jobs:
  Create-Artifact:
    name: Artifact-Producer
    runs-on: ubuntu-latest
    steps:
      - name: Creating the Artifact
        run: echo "Testing artifacts" >> artifacts.txt

      - name: Upload-Artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-artifact
          path: artifact.txt

  Download-Artifact:
    name: Artifact-Downloader
    needs:  Create-Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Downloading-Artifact
        uses: actions/download-artifact@v4
        with:
          name: test-artifact

      - name: Cat Artifact
        run: cat artifact.txt

        
       

