name: Deploy 

on:
  push:
    branches:
      - main

env:
  WORKFLOW_ENV: hello_world

jobs:
  checkout:
    runs-on: ubuntu-latest
    outputs:
      bucket_output: ${{ steps.bucket.outputs.bucket }}
    steps:
      - uses: actions/checkout@v4
      - name: Clone Repo
        id: bucket
        run: |
          echo "Cloned Repo"
          echo "bucket=YO bigg dawg" >> "$GITHUB_OUTPUT"


  testing_types:
     runs-on: ubuntu-latest
     needs:
       - checkout

     steps:
       - name: Testing
         run: |
           echo "DONE $WORKFLOW_ENV"
           echo "${{ needs.checkout.outputs.bucket_output}}"

  third_job:
    runs-on: ubuntu-latest
    needs:
      - testing_types
    steps:
      - name: step 1 within job 3
        run: |
          echo "Testing Things"




       

